import 'package:flutter/material.dart';
import 'package:ijato/app/models/schedule.dart';

class ScheduleController with ChangeNotifier {
  List<Schedule> schedules = [
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
  ];

  void changeStatus(int index, ScheduleStatus status) {
    schedules[index].status = status;
    notifyListeners();
  }
}
