import 'package:flutter/material.dart';
import 'package:ijato/app/models/schedule.dart';

class ScheduleController with ChangeNotifier {
  List<Schedule> schedules = [
    Schedule(
      date: "03/06/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "04/06/2024",
      time: "09:00 às 10:00",
      name: "Ana Silva",
      vehicle: "Carro",
      brand: "Honda",
      model: "Civic",
      plate: "ABC-1234",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "05/06/2024",
      time: "10:00 às 11:00",
      name: "Carlos Souza",
      vehicle: "Carro",
      brand: "Toyota",
      model: "Corolla",
      plate: "XYZ-5678",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "06/06/2024",
      time: "11:00 às 12:00",
      name: "Mariana Lima",
      vehicle: "Carro",
      brand: "Chevrolet",
      model: "Onix",
      plate: "DEF-9012",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "07/06/2024",
      time: "12:00 às 13:00",
      name: "João Pereira",
      vehicle: "Carro",
      brand: "Ford",
      model: "Fiesta",
      plate: "GHI-3456",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "08/06/2024",
      time: "13:00 às 14:00",
      name: "Fernanda Costa",
      vehicle: "Carro",
      brand: "Volkswagen",
      model: "Golf",
      plate: "JKL-7890",
      schedule: "Higienização completa",
      status: ScheduleStatus.unavailable,
    ),
    Schedule(
      date: "09/06/2024",
      time: "14:00 às 15:00",
      name: "Ricardo Almeida",
      vehicle: "Carro",
      brand: "Hyundai",
      model: "HB20",
      plate: "MNO-1234",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "10/06/2024",
      time: "15:00 às 16:00",
      name: "Patrícia Santos",
      vehicle: "Carro",
      brand: "Renault",
      model: "Duster",
      plate: "PQR-5678",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
    Schedule(
      date: "11/06/2024",
      time: "16:00 às 17:00",
      name: "Lucas Oliveira",
      vehicle: "Carro",
      brand: "Nissan",
      model: "Kicks",
      plate: "STU-9012",
      schedule: "Higienização completa",
      status: ScheduleStatus.available,
    ),
  ];

  void changeStatus(int index, ScheduleStatus status) {
    schedules[index].status = status;
    notifyListeners();
  }
}
